#ifndef _HTML_TYPE_
#define _HTML_TYPE_

#define LESS_THAN_SIGN		'<'
#define GREATER_THAN_SIGN	'>'
#define SLASH				'/'
#define BLANK				' '

enum E_HTML_TAG_RET_TYPE
{
	E_HTML_TAG_RET_START = 0,
	E_HTML_TAG_RET_END,

	E_HTML_TAG_FOUND,
	E_HTML_TAG_NOT_FOUND,

	E_HTML_TAG_PARSE_FAIL,

	E_HTML_TAG_RET_UNKNOWN
};

enum E_HTML_TYPE
{
	E_HTML_COMMENT = 0,
	E_HTML_DOCTYPE,
	E_HTML_a,
	E_HTML_abbr,
	E_HTML_acronym,
	E_HTML_address,
	E_HTML_applet,
	E_HTML_area,
	E_HTML_article,
	E_HTML_aside,
	E_HTML_audio,
	E_HTML_b,
	E_HTML_base,
	E_HTML_basefont,
	E_HTML_bdi,
	E_HTML_bdo,
	E_HTML_big,
	E_HTML_blockquote,
	E_HTML_body,
	E_HTML_br,
	E_HTML_button,
	E_HTML_canvas,
	E_HTML_caption,
	E_HTML_center,
	E_HTML_cite,
	E_HTML_code,
	E_HTML_col,
	E_HTML_colgroup,
	E_HTML_datalist,
	E_HTML_dd,
	E_HTML_del,
	E_HTML_details,
	E_HTML_dfn,
	E_HTML_dialog,
	E_HTML_dir,
	E_HTML_div,
	E_HTML_dl,
	E_HTML_dt,
	E_HTML_em,
	E_HTML_embed,
	E_HTML_fieldset,
	E_HTML_figcaption,
	E_HTML_figure,
	E_HTML_font,
	E_HTML_footer,
	E_HTML_form,
	E_HTML_frame,
	E_HTML_frameset,
	E_HTML_h1,
	E_HTML_h2,
	E_HTML_h3,
	E_HTML_h4,
	E_HTML_h5,
	E_HTML_h6,
	E_HTML_head,
	E_HTML_header,
	E_HTML_hr,
	E_HTML_html,
	E_HTML_i,
	E_HTML_iframe,
	E_HTML_img,
	E_HTML_input,
	E_HTML_ins,
	E_HTML_kbd,
	E_HTML_keygen,
	E_HTML_label,
	E_HTML_legend,
	E_HTML_li,
	E_HTML_link,
	E_HTML_main,
	E_HTML_map,
	E_HTML_mark,
	E_HTML_menu,
	E_HTML_menuitem,
	E_HTML_meta,
	E_HTML_meter,
	E_HTML_nav,
	E_HTML_noframes,
	E_HTML_noscript,
	E_HTML_object,
	E_HTML_ol,
	E_HTML_optgroup,
	E_HTML_option,
	E_HTML_output,
	E_HTML_p,
	E_HTML_param,
	E_HTML_pre,
	E_HTML_progress,
	E_HTML_q,
	E_HTML_rp,
	E_HTML_rt,
	E_HTML_ruby,
	E_HTML_s,
	E_HTML_samp,
	E_HTML_script,
	E_HTML_section,
	E_HTML_select,
	E_HTML_small,
	E_HTML_source,
	E_HTML_span,
	E_HTML_strike,
	E_HTML_strong,
	E_HTML_style,
	E_HTML_sub,
	E_HTML_summary,
	E_HTML_sup,
	E_HTML_table,
	E_HTML_tbody,
	E_HTML_td,
	E_HTML_textarea,
	E_HTML_tfoot,
	E_HTML_th,
	E_HTML_thead,
	E_HTML_time,
	E_HTML_title,
	E_HTML_tr,
	E_HTML_track,
	E_HTML_tt,
	E_HTML_u,
	E_HTML_ul,
	E_HTML_var,
	E_HTML_video,

	E_HTML_UNKNOWN
};

//struct ST_TAG_TYPE
//{
//	E_HTML_TYPE	eHTMLType;
//	CHAR		*pTag;
//} stTagType[] = {
//	{ E_HTML_COMMENT, "!--" },
//	{ E_HTML_DOCTYPE, "DOCTYPE" },
//	{ E_HTML_a, "a" },
//	{ E_HTML_abbr, "abbr" },
//	{ E_HTML_acronym, "acronym" },
//	{ E_HTML_address, "address" },
//	{ E_HTML_applet, "applet" },
//	{ E_HTML_area, "area" },
//	{ E_HTML_article, "article" },
//	{ E_HTML_aside, "aside" },
//	{ E_HTML_audio, "audio" },
//	{ E_HTML_b, "b" },
//	{ E_HTML_base, "base" },
//	{ E_HTML_basefont, "basefont" },
//	{ E_HTML_bdi, "bdi" },
//	{ E_HTML_bdo, "bdo" },
//	{ E_HTML_big, "big" },
//	{ E_HTML_blockquote, "blockquote" },
//	{ E_HTML_body, "body" },
//	{ E_HTML_br, "br" },
//	{ E_HTML_button, "button" },
//	{ E_HTML_canvas, "canvas" },
//	{ E_HTML_caption, "caption" },
//	{ E_HTML_center, "center" },
//	{ E_HTML_cite, "cite" },
//	{ E_HTML_code, "code" },
//	{ E_HTML_col, "col" },
//	{ E_HTML_colgroup, "colgroup" },
//	{ E_HTML_datalist, "datalist" },
//	{ E_HTML_dd, "dd" },
//	{ E_HTML_del, "del" },
//	{ E_HTML_details, "details" },
//	{ E_HTML_dfn, "dfn" },
//	{ E_HTML_dialog, "dialog" },
//	{ E_HTML_dir, "dir" },
//	{ E_HTML_div, "div" },
//	{ E_HTML_dl, "dl" },
//	{ E_HTML_dt, "dt" },
//	{ E_HTML_em, "em" },
//	{ E_HTML_embed, "embed" },
//	{ E_HTML_fieldset, "fieldset" },
//	{ E_HTML_figcaption, "figcaption" },
//	{ E_HTML_figure, "figure" },
//	{ E_HTML_font, "font" },
//	{ E_HTML_footer, "footer" },
//	{ E_HTML_form, "form" },
//	{ E_HTML_frame, "frame" },
//	{ E_HTML_frameset, "frameset" },
//
//	{ E_HTML_h1, "h1" },
//	{ E_HTML_h2, "h2" },
//	{ E_HTML_h3, "h3" },
//	{ E_HTML_h4, "h4" },
//	{ E_HTML_h5, "h5" },
//	{ E_HTML_h6, "h6" },
//
//	{ E_HTML_head, "head" },
//	{ E_HTML_header, "header" },
//	{ E_HTML_hr, "hr" },
//	{ E_HTML_html, "html" },
//	{ E_HTML_i, "i" },
//	{ E_HTML_iframe, "iframe" },
//	{ E_HTML_img, "img" },
//	{ E_HTML_input, "input" },
//	{ E_HTML_ins, "ins" },
//	{ E_HTML_kbd, "kbd" },
//	{ E_HTML_keygen, "keygen" },
//	{ E_HTML_label, "label" },
//	{ E_HTML_legend, "legend" },
//	{ E_HTML_li, "li" },
//	{ E_HTML_link, "link" },
//	{ E_HTML_main, "main" },
//	{ E_HTML_map, "map" },
//	{ E_HTML_mark, "mark" },
//	{ E_HTML_menu, "menu" },
//	{ E_HTML_menuitem, "menuitem" },
//	{ E_HTML_meta, "meta" },
//	{ E_HTML_meter, "meter" },
//	{ E_HTML_nav, "nav" },
//	{ E_HTML_noframes, "noframes" },
//	{ E_HTML_noscript, "noscript" },
//	{ E_HTML_object, "object" },
//	{ E_HTML_ol, "ol" },
//	{ E_HTML_optgroup, "optgroup" },
//	{ E_HTML_option, "option" },
//	{ E_HTML_output, "output" },
//	{ E_HTML_p, "p" },
//	{ E_HTML_param, "param" },
//	{ E_HTML_pre, "pre" },
//	{ E_HTML_progress, "progress" },
//	{ E_HTML_q, "q" },
//	{ E_HTML_rp, "rp" },
//	{ E_HTML_rt, "rt" },
//	{ E_HTML_ruby, "ruby" },
//	{ E_HTML_s, "s" },
//	{ E_HTML_samp, "samp" },
//	{ E_HTML_script, "script" },
//	{ E_HTML_section, "section" },
//	{ E_HTML_select, "select" },
//	{ E_HTML_small, "small" },
//	{ E_HTML_source, "source" },
//	{ E_HTML_span, "span" },
//	{ E_HTML_strike, "strike" },
//	{ E_HTML_strong, "strong" },
//	{ E_HTML_style, "style" },
//	{ E_HTML_sub, "sub" },
//	{ E_HTML_summary, "summary" },
//	{ E_HTML_sup, "sup" },
//	{ E_HTML_table, "table" },
//	{ E_HTML_tbody, "tbody" },
//	{ E_HTML_td, "td" },
//	{ E_HTML_textarea, "textarea" },
//	{ E_HTML_tfoot, "tfoot" },
//	{ E_HTML_th, "th" },
//	{ E_HTML_thead, "thread" },
//	{ E_HTML_time, "time" },
//	{ E_HTML_title, "title" },
//	{ E_HTML_tr, "tr" },
//	{ E_HTML_track, "track" },
//	{ E_HTML_tt, "tt" },
//	{ E_HTML_u, "u" },
//	{ E_HTML_ul, "ul" },
//	{ E_HTML_var, "var" },
//	{ E_HTML_video, "video" },
//};

#endif 